### ISSUE TITLE
DD for V12?

### ISSUE THREAD

**Issue by mcubas76** [mcglincy/dungeondraw-foundry-vtt#131]
Hi. Would like to know if you are working to get this module running in V12. It is an awesome module that is super helpful. Thanks!

**Comment by pbtura** [comment]
I would like to know as well. This is one of the last modules keeping me from migrating to v12.

**Comment by mcglincy** [comment]
Unfortunately job & life have been busy, and I haven't had any free time to fix breakage introduced by v12. I do plan to eventually update Dungeon Draw, but I don't have a concrete estimate when. Right now I'm working my way through all my various systems and modules, to fix them for v12.

**Comment by pbtura** [comment]
No problem. Good to know the module is still alive and kicking. This is an amazing tool.

**Comment by mcglincy** [comment]
I fixed the obvious v12 breakage and pushed a new Dungeon Draw 3.0.0 build, now compatible with Foundry v12. It may still have lurking bugs, so please let me know if you run into any :)

https://github.com/mcglincy/dungeondraw-foundry-vtt/releases/tag/3.0.0

**Comment by pbtura** [comment]
Appreciate the effort. I'm definitely running into some bugs. I keep getting and error about 'addChild'. Once I get a stacktrace, I'll post a bug report.

**Comment by sharkbruhaha** [comment]
also getting it
![image](https://github.com/mcglincy/dungeondraw-foundry-vtt/assets/44031572/8fc15ba2-5d19-4467-a141-2c80d1e8eceb)
I can't even create a new scene and go to it without hitting it :(

**Comment by sharkbruhaha** [comment]
![image](https://github.com/mcglincy/dungeondraw-foundry-vtt/assets/44031572/5e974e5f-0654-4bf1-b489-6d19a52118b3)

**Comment by mcglincy** [comment]
ok, some followup questions:
- what Foundry version, OS, and browser are y'all using? 
- have you tried with all other modules disabled?
- can you provide exact steps to reproduce the addChild error?

I'm not see the addChild error on FoundryVTT-12.328, node.js build on macos, using Chrome browser.

Here's the simple test I've been doing:
- create a new 5e world
- go to manage modules and enable Dungeon Draw
- create a new scene
- click the dungeon draw toolbar button
- draw a rectangle room on the map

**Comment by mcglincy** [comment]
ok - stupid error on my part... I forgot to actually merge the new v12 code before building :P

I just pushed a new build 3.0.1, with the v12 fixes this time.

**Comment by zbyers26** [comment]
I still see this error on 3.0.1. I can disable BaileyWiki modules (a number of them) and then it works. So there might be some more compatibility issues going on here outside just with DD itself.

**Comment by mcglincy** [comment]
Chatting and debugging on the Baileywiki discord #foundryvtt channel, to see if we can narrow down exactly which module(s) are conflicting, and how.

**Comment by sharkbruhaha** [comment]
> ok - stupid error on my part... I forgot to actually merge the new v12 code before building :P
> 
> I just pushed a new build 3.0.1, with the v12 fixes this time.

hah! done that too many times before

**Comment by BladeFireLight** [comment]
I see the error with only dungeon draw enabled

**Comment by mcglincy** [comment]
@BladeFireLight what OS, Foundry version, and browser are you using? 

So far I haven't been able to repro the error on my local setup (Foundry 12.328 node.js build, running on macOS, either chrome or Firefox browsers).

**Comment by pbtura** [comment]
I found something interesting that may be helpful. The scenes that are
active when you open the game world seems to matter.

I have a custom scene that I created using DD and a premade (Galleon
Airship) from Baileywiki. If my scene is the only one open initially and
then I go and open the other scene everything is fine. However, if the
Baileywiki scene is in the navigation bar when I load the world then I get
the 'addChild' error.

What is even more strange is that the Baileywiki modules don't seem to
matter. I deactivated all of them and I still see this behavior when I have
one of their maps and a DD map open when the world loads.

FYI, I'm using the latest version of Chrome on Windows 11.

**Comment by mcglincy** [comment]
Thanks @pbtura - following your steps I'm now able to repro. If I have a Baileywiki scene activated, when I refresh the browser tab I see the error. If I have a DD scene activated, when I refresh the browser tab I don't see the error.

Now to debug what is actually making that error and how to fix it :)

**Comment by PXR5** [comment]
I've just been testing with FVTT 12.328, OSE 1.10.3 and Dungeondraw 3.0.1 and I was also getting the 'reading addChild' problem, no scenes (using Dungeondraw or not) were visible although they seemed to load. I found disabling the Dungeondraw module, loading a scene (with a Dungeondraw map), seeing all the walls and other items but not the map of course, then re-enabling the module then loading the scene again, now has all scenes loading correctly.

I just restarted Foundry for good measure and scenes are now displaying normally, no sign of the error.

Tested with Brave browser on macos 14.5, Brave [Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64)]

**Comment by mcglincy** [comment]
It looks like DungeonDraw's "DungeonLayer" layer being on the canvas is somehow confusing other parts of Foundry, causing an InterfaceCanvasGroup object to exist with an undefined #drawings collection, which then throws an error when #drawings.addChild() is called as part of drawing various other Drawings. (In my testing, it was a drawing on the Baileywiki scene that was attempting to draw.)

I need to dig more through Foundry code to understand how/why the DungeonLayer is causing this badness in v12. It could be it's missing some new v12 layer option/field, etc.

**Comment by pbtura** [comment]
I noticed there is a new field called 'sort' for tokens that seems to have
replaced the z index. Not sure if it is related but it might be a good
place to start

**Comment by mcglincy** [comment]
Changing DungeonLayer to be in group "interface" -- rather than "primary" -- makes the addChild error go away. 

Now I'm working through why drawings are incorrectly showing up below the DungeonLayer, even though I've got the DungeonLayer's zIndex set lower than DrawingsLayer's zIndex.

**Comment by mcglincy** [comment]
I believe I've found how to both keep Dungeon Draw in the primary group and avoid drawing all other drawings in the scene (which causes the addChild error when Dungeon Draw is in the primary group).

New build 3.0.2 released, if folks want to grab it and test.

Ultimately, Dungeon Draw should probably stop extending the Foundry PlaceablesLayer and/or stop using the Foundry Drawings class for its tool previews... because when new versions of Foundry change how these things work or are drawn, it breaks things with Dungeon Draw.

**Comment by PXR5** [comment]
It's working ok now for me. Tested with FVTT 12.328, Brave Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64) on macOS 14.5.

**Comment by mcglincy** [comment]
Going to close this issue. If anyone hits more v12 bugs, please file new github issues or ping me on discord (mcglintlock on the Foundry discord).
